{"url": "https://towardsdatascience.com/connect-to-azure-sql-server-using-python-76eba1fb458b", "time": 1683018511.308933, "path": "towardsdatascience.com/connect-to-azure-sql-server-using-python-76eba1fb458b/", "scrape_status": {"code": 4, "message": "invalid response status code", "resp_status_code": 429}}