{"url": "https://towardsdatascience.com/the-match-case-in-python-3-10-is-not-that-simple-f65b350bb025", "time": 1683019373.088458, "path": "towardsdatascience.com/the-match-case-in-python-3-10-is-not-that-simple-f65b350bb025/", "scrape_status": {"code": 4, "message": "invalid response status code", "resp_status_code": 429}}