{"url": "https://towardsdatascience.com/on-the-seriousness-of-ai-applications-f512fd3ced56", "time": 1683019063.306349, "path": "towardsdatascience.com/on-the-seriousness-of-ai-applications-f512fd3ced56/", "scrape_status": {"code": 4, "message": "invalid response status code", "resp_status_code": 429}}